services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    environment:
      - PYTHONPATH=/app
    ports:
      - "8000:8000"
  db:
    image: postgres:14.2-alpine
    container_name: fastapi_postgres
    restart: always
    env_file:
      .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"

volumes:
  postgres_data:
